services:

  #MariaDB
    mariadb:
      image: mariadb:user
      container_name: mariadb
      build: ./MariaDB
      volumes:
        - mariadb:/var/lib/mysql
      env_file:
        - .env
      networks:
        - inception
      restart: always
      healthcheck:
        test: ["CMD", "nc", "-zv", "mariadb", "3306"]
        interval: 1s
        timeout: 5s
        retries: 10
  #WordPress
    wordpress:
      image: wordpress:user
      container_name: wordpress
      build: ./WordPress
      depends_on:
        mariadb:
          condition: service_healthy
      volumes:
        - wordpress:/var/www/wordpress
      env_file:
        - .env
      networks:
        - inception
      restart: always
  #NGINX
    nginx:
      image: nginx:user
      container_name: nginx
      build: ./NGINX
      ports:
        - "443:443"
      depends_on:
        - wordpress
      volumes:
        - wordpress:/var/www/wordpress
      networks:
        - inception
      restart: always
      

volumes:
    mariadb:
      name: mariadb
      driver: local
      driver_opts:
        device: /home/acatusse/data/mariadb
        o: bind
        type: none
    wordpress:
      name: wordpress
      driver: local
      driver_opts:
        device: /home/acatusse/data/wordpress
        o: bind
        type: none

networks:
  inception:
    name: inception